# Generated by Django 5.2.7 on 2025-12-21 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'მოლოდინში'), ('confirmed', 'დადასტურებული'), ('cancelled', 'გაუქმებული'), ('completed', 'დასრულებული')], default='confirmed', max_length=20, verbose_name='სტატუსი')),
                ('attended', models.BooleanField(default=False, verbose_name='დაესწრო')),
                ('notes', models.TextField(blank=True, verbose_name='შენიშვნები')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='ჩაწერის დრო')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ჩაწერა',
                'verbose_name_plural': 'ჩაწერები',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='დაწყების თარიღი')),
                ('end_date', models.DateField(verbose_name='დასრულების თარიღი')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='ავტომატური განახლება')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'საწევრო',
                'verbose_name_plural': 'საწევროები',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='სახელი')),
                ('description', models.TextField(blank=True, verbose_name='აღწერა')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ფასი')),
                ('duration_days', models.IntegerField(help_text='რამდენი დღით', validators=[django.core.validators.MinValueValidator(1)], verbose_name='ხანგრძლივობა')),
                ('max_trainings_per_week', models.IntegerField(help_text='კვირაში რამდენ ვარჯიშზე', validators=[django.core.validators.MinValueValidator(1)], verbose_name='ვარჯიშები კვირაში')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'საწევროს პაკეტი',
                'verbose_name_plural': 'საწევროს პაკეტები',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='სახელი')),
                ('description', models.TextField(blank=True, verbose_name='აღწერა')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sports/', verbose_name='სურათი')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'სპორტი',
                'verbose_name_plural': 'სპორტები',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='სათაური')),
                ('description', models.TextField(blank=True, verbose_name='აღწერა')),
                ('difficulty', models.CharField(choices=[('beginner', 'დამწყები'), ('intermediate', 'საშუალო'), ('advanced', 'მოწინავე')], default='beginner', max_length=20, verbose_name='სირთულე')),
                ('date', models.DateField(verbose_name='თარიღი')),
                ('start_time', models.TimeField(verbose_name='დაწყების დრო')),
                ('duration', models.IntegerField(help_text='წუთებში', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(300)], verbose_name='ხანგრძლივობა')),
                ('max_participants', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='მაქსიმალური მონაწილეები')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ვარჯიში',
                'verbose_name_plural': 'ვარჯიშები',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
