# Generated by Django 5.2.7 on 2025-12-21 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი'),
        ),
        migrations.AddField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='sports.membershipplan', verbose_name='პაკეტი'),
        ),
        migrations.AddField(
            model_name='training',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'coach']}, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='მწვრთნელი'),
        ),
        migrations.AddField(
            model_name='training',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='sports.sport', verbose_name='სპორტი'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sports.training', verbose_name='ვარჯიში'),
        ),
        migrations.AlterUniqueTogether(
            name='training',
            unique_together={('coach', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'training')},
        ),
    ]
